version: '3'

services:
  app:
    build: .
    environment:
      - PORT=3000
    ports:
      - "3000" 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]  # Check if the app responds to a GET request on / route
      interval: 5s        # How often to check the health (every 30 seconds)
      retries: 2          # How many retries before considering the container unhealthy
      timeout: 3s         # How long to wait for a response before considering the check failed
      start_period: 5s    # Initial startup delay for the container to become ready
  loadbalancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
 # Adding a health check to the load balancer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]  # Check if Nginx responds on the main route
      interval: 30s        # How often to check the health (every 30 seconds)
      retries: 3           # How many retries before considering the container unhealthy
      timeout: 10s         # How long to wait for a response before considering the check failed
      start_period: 10s    # Initial startup delay for the container to become ready